# hostname of the host serving massbank
host: &commonHost msbi.ipb-halle.de
# base path of the public url serving massbank
pathPrefix: &commonPathPrefix MassBank
# release name of the helm install of massbank3-frontend, required for dbtool
# to identify the hostname of the postgres database
massbankReleaseName: massbank

# postgres settings
# the password for the postgres admin user
postgresPassword: &commonPostgresPassword "massbankAdminPassword"
# the username for the postgres user
username: &commonUsername "massbank"
# the password for the postgres user
password: &commonPassword "massbankPassword"
# the name of the postgres database
database: &commonDatabase "massbank"


# set the values in the dependencies, do not change
massbank-export-api:
  host: *commonHost
  pathPrefix: *commonPathPrefix
massbank-api:
  host: *commonHost
  pathPrefix: *commonPathPrefix
  postgresql:
    auth:
      postgresPassword: *commonPostgresPassword
      username: *commonUsername
      password: *commonPassword
      database: *commonDatabase
    primary:
      initdb:
        password: *commonPostgresPassword
  massbank-similarity-api:
    host: *commonHost
    pathPrefix: *commonPathPrefix

