# hostname of the host serving massbank
host: &commonHost massbank.eu
# base path of the public url serving massbank
pathPrefix: &commonPathPrefix MassBank
# release name of the helm install of massbank3-frontend, required for dbtool
# to identify the hostname of the postgres database
massbankReleaseName: massbank

# postgres settings
# the password for the postgres admin user
postgresPassword: &commonPostgresPassword "msbi-raab"
# the username for the postgres user
username: &commonUsername "massbank"
# the password for the postgres user
password: &commonPassword "msbi-raab  "
# the name of the postgres database
database: &commonDatabase "massbank"

HTML_HEAD_FILE: "/html-insert/html-head.html"
HTML_HEAD_FILE_CONTENT: |
  <meta name="google-site-verification" content="HUHU_Test_1234">
  <script src="https://www.ufz.de/stats/piwik.js"></script>
HTML_BODY_FILE: ""
HTML_BODY_FILE_CONTENT: |
  <div id="data-privacy-container" style="display: none; text-align: center">
    <p style="text-align: left">
      This website uses technical necessary cookies (e.g. session ID) and in
      addition the Matomo web analytics tool. Matomo enables us to evaluate the
      use of our website in compliance with GDPR (Directive 95/46/EC).
    </p>
    <div style="text-align: left">
      <a href="https://www.ufz.de/index.php?en=44326" target="_blank"
        >Data Privacy Policy</a
      >
    </div>
    <p style="text-align: left">
      This window can be opened with the 'Data Privacy'-button in the footer
      section. Your consent to the use of Matomo can be revoked any time. To make
      that choice, please un-check below.
    </p>
    <div
      id="checkbox-container"
      style="
        display: flex;
        justify-content: left;
        align-items: center;
        margin-top: 10px;
      "
    >
      <label id="checkbox-label" style="font-weight: bold"
        >Click here to disable or allow the tracking:</label
      ><input
        type="checkbox"
        id="analytics-checkbox"
        style="width: 18px; height: 18px; margin-left: 20px"
        onchange="handleOnChange(this.checked)"
      />
    </div>
  </div>

  <script>
    function handleOnChange(checked) {
      setAnalytics(checked);
    }

    function setAnalytics(checked) {
      localStorage.setItem("analytics", checked ? "1" : "0");

      if (checked === true) {
        try {
          const piwikTracker = Piwik.getTracker(
            "https://www.ufz.de/stats/piwik.php",
            24
          );
          piwikTracker.requireConsent();
          piwikTracker.trackPageView();
          piwikTracker.enableLinkTracking();
          piwikTracker.setConsentGiven();
          // console.log("piwikTracker.setConsentGiven()");
        } catch (err) {}
      } else {
        // console.log("setAnalytics() - no tracking");
      }
    }

    window.onload = function () {
      const localStorageItem = localStorage.getItem("analytics");
      // console.log("localStorage.getItem('analytics'): " + localStorageItem);
      const analyticsCheckbox = document.getElementById("analytics-checkbox");
      if (localStorageItem === null) {
        localStorage.setItem("analytics", "1");
        analyticsCheckbox.setAttribute("checked", true);
        setAnalytics(true);
        // Show the modal if no choice has been made yet
        window.showDataPrivacyModal = true;
      } else {
        window.showDataPrivacyModal = false;
        if (localStorageItem === "1") {
          analyticsCheckbox.setAttribute("checked", true);
          setAnalytics(true);
        } else {
          setAnalytics(false);
        }
      }
    };
  </script>
DISTRIBUTOR_TEXT: "This website is hosted and distributed by the Helmholtz-Zentrum für Umweltforschung GmbH - UFZ, Leipzig, Germany."
DISTRIBUTOR_URL: "https://www.ufz.de/index.php?en=36683"
MB3_FRONTEND_BROWSER_TAB_TITLE: "MassBank"
MB3_FRONTEND_HOMEPAGE_INTRO_TEXT: "Welcome to MassBank, an open-source mass spectral library for the identification of small chemical molecules of metabolomics, exposomics and environmental relevance."
MB3_FRONTEND_HOMEPAGE_NEWS_SECTION_TEXT: ""
MB3_FRONTEND_HOMEPAGE_FUNDING_SECTION_TEXT: ""
MB3_FRONTEND_HOMEPAGE_ADDITIONAL_SECTION_NAME: ""
MB3_FRONTEND_HOMEPAGE_ADDITIONAL_SECTION_TEXT: ""

# set the values in the dependencies, do not change
massbank-export-api:
  host: *commonHost
  pathPrefix: *commonPathPrefix
massbank-api:
  host: *commonHost
  pathPrefix: *commonPathPrefix
  postgresql:
    auth:
      postgresPassword: *commonPostgresPassword
      username: *commonUsername
      password: *commonPassword
      database: *commonDatabase
    primary:
      initdb:
        password: *commonPostgresPassword
  massbank-similarity-api:
    host: *commonHost
    pathPrefix: *commonPathPrefix

