apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "massbank-similarity-api.fullname" . }}-env-configmap
  labels:
    {{- include "massbank-similarity-api.labels" . | nindent 4 }}
data:
  MSP: "/msp/MassBank.msp"