apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "massbank-export-api.fullname" . }}-env-configmap
  labels:
    {{- include "massbank-export-api.labels" . | nindent 4 }}
data:
  MB_DATA_DIRECTORY: "/MassBank-data"
  CORS_ALLOWED_ORIGINS: "https://{{ .Values.host }}/{{ .Values.pathPrefix }}/"
  CONTEXT_PATH: "/{{ .Values.pathPrefix }}-export"