# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

postgresPassword: "massbankAdminPassword"
username: "massbank"
password: "massbankPassword"
database: "massbank"

massbankReleaseName: massbank

image:
  repository: quay.io/massbank/massbank-dbtool

# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels:
  app: massbank-dbtool