apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "massbank-frontend.fullname" . }}-env-configmap
  labels:
    {{- include "massbank-frontend.labels" . | nindent 4 }}
data:
  MB3_API_URL: "https://{{ .Values.host }}/{{ .Values.pathPrefix }}-api"
  MB3_API_URL_INTERNAL: "http://{{ .Release.Name }}-massbank-api:8080/{{ .Values.pathPrefix }}-api"
  MB3_FRONTEND_URL: "https://{{ .Values.host }}"
  MB3_FRONTEND_BASE_URL: "/{{ .Values.pathPrefix }}"
  MB3_FRONTEND_VERSION: "3.0.0 (beta)"
  EXPORT_SERVICE_URL: "https://{{ .Values.host }}/{{ .Values.pathPrefix }}-export"
  EXPORT_SERVICE_URL_INTERNAL: "http://{{ .Release.Name }}-massbank-export-api:8080/{{ .Values.pathPrefix }}-export"
  GOOGLE_SEARCH_CONSOLE_KEY: "o3yPKbs7xQhjmcT8HdNIDFFlIXdkBm2Y8GYJrr3UH6o"
  DISTRIBUTOR_TEXT: "This website is hosted and distributed by the Leibniz Institute of Plant Biochemistry, Halle (Saale), Germany."
  DISTRIBUTOR_URL: "https://www.ipb-halle.de/kontakt/impressum"
  MB3_FRONTEND_BROWSER_TAB_TITLE: "MassBank"
  MB3_FRONTEND_HOMEPAGE_INTRO_TEXT: "Welcome to MassBank, an open-source mass spectral library for the identification of small chemical molecules of metabolomics, exposomics and environmental relevance."