{{- if .Values.HTML_BODY_FILE }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: html-body
  labels:
    {{- include "massbank-frontend.labels" . | nindent 4 }}
data:
  html-body.html: |-
    {{ .Values.HTML_BODY_FILE_CONTENT | nindent 4}}
{{- end }}