apiVersion: v2
name: massbank-api
description: A Helm chart for massbank-api

type: application
version: 0.1.0
appVersion: "v2025.05.1"


dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 16.6.2
  - name: massbank-similarity-api
    repository: file://../massbank-similarity-api
    version: 0.1.0