apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "massbank-similarity-api.fullname" . }}-env-configmap
  labels:
    {{- include "massbank-similarity-api.labels" . | nindent 4 }}
data:
  DATA_DIR: "/MassBank-data"
  VERBOSE: "true"
  CONTEXT_PATH: "/{{ .Values.pathPrefix }}-similarity"